# Generated by Django 4.2.8 on 2023-12-20 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_alter_animal_breed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='breed',
        ),
        migrations.AddField(
            model_name='animal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
