# Generated by Django 4.2.8 on 2023-12-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_animal_category_animal_breed_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('salary', models.FloatField(default=1)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
