# Generated by Django 4.2.8 on 2023-12-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='age',
            field=models.FloatField(default=1),
        ),
    ]
